alter table public.users alter column id drop identity if exists;

insert into public.users (id, created_at, provider, provider_id, email, name, void)
values (99, now(), 'manual', 'manual', 'admin@aicoua.com.ua', 'Service admin', true);

alter table public.users alter column id add generated by default as identity (start with 100);