create extension if not exists "vector" with schema "extensions";


create table "public"."a2v10_chank" (
    "id" bigint generated by default as identity not null,
    "content" text not null,
    "part_id" bigint not null,
    "vector" vector
);


create table "public"."a2v10_help" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "content" text default ''::text
);


CREATE UNIQUE INDEX a2v10_chank_pkey ON public.a2v10_chank USING btree (id, content);

CREATE UNIQUE INDEX a2v10_help_pkey ON public.a2v10_help USING btree (id);

alter table "public"."a2v10_chank" add constraint "a2v10_chank_pkey" PRIMARY KEY using index "a2v10_chank_pkey";

alter table "public"."a2v10_help" add constraint "a2v10_help_pkey" PRIMARY KEY using index "a2v10_help_pkey";

alter table "public"."a2v10_chank" add constraint "a2v10_chank_part_id_fkey" FOREIGN KEY (part_id) REFERENCES a2v10_help(id) not valid;

alter table "public"."a2v10_chank" validate constraint "a2v10_chank_part_id_fkey";

grant delete on table "public"."a2v10_chank" to "anon";

grant insert on table "public"."a2v10_chank" to "anon";

grant references on table "public"."a2v10_chank" to "anon";

grant select on table "public"."a2v10_chank" to "anon";

grant trigger on table "public"."a2v10_chank" to "anon";

grant truncate on table "public"."a2v10_chank" to "anon";

grant update on table "public"."a2v10_chank" to "anon";

grant delete on table "public"."a2v10_chank" to "authenticated";

grant insert on table "public"."a2v10_chank" to "authenticated";

grant references on table "public"."a2v10_chank" to "authenticated";

grant select on table "public"."a2v10_chank" to "authenticated";

grant trigger on table "public"."a2v10_chank" to "authenticated";

grant truncate on table "public"."a2v10_chank" to "authenticated";

grant update on table "public"."a2v10_chank" to "authenticated";

grant delete on table "public"."a2v10_chank" to "service_role";

grant insert on table "public"."a2v10_chank" to "service_role";

grant references on table "public"."a2v10_chank" to "service_role";

grant select on table "public"."a2v10_chank" to "service_role";

grant trigger on table "public"."a2v10_chank" to "service_role";

grant truncate on table "public"."a2v10_chank" to "service_role";

grant update on table "public"."a2v10_chank" to "service_role";

grant delete on table "public"."a2v10_help" to "anon";

grant insert on table "public"."a2v10_help" to "anon";

grant references on table "public"."a2v10_help" to "anon";

grant select on table "public"."a2v10_help" to "anon";

grant trigger on table "public"."a2v10_help" to "anon";

grant truncate on table "public"."a2v10_help" to "anon";

grant update on table "public"."a2v10_help" to "anon";

grant delete on table "public"."a2v10_help" to "authenticated";

grant insert on table "public"."a2v10_help" to "authenticated";

grant references on table "public"."a2v10_help" to "authenticated";

grant select on table "public"."a2v10_help" to "authenticated";

grant trigger on table "public"."a2v10_help" to "authenticated";

grant truncate on table "public"."a2v10_help" to "authenticated";

grant update on table "public"."a2v10_help" to "authenticated";

grant delete on table "public"."a2v10_help" to "service_role";

grant insert on table "public"."a2v10_help" to "service_role";

grant references on table "public"."a2v10_help" to "service_role";

grant select on table "public"."a2v10_help" to "service_role";

grant trigger on table "public"."a2v10_help" to "service_role";

grant truncate on table "public"."a2v10_help" to "service_role";

grant update on table "public"."a2v10_help" to "service_role";


