create type "public"."servise_types" as enum ('function', 'mcp_sse', 'mcp_stream');

create table "public"."servises" (
    "id" bigint generated by default as identity not null,
    "type" servise_types,
    "name" character varying,
    "description" text
);


alter table "public"."tokens" alter column "token" set default '''500''::character varying'::character varying;

CREATE UNIQUE INDEX servises_pkey ON public.servises USING btree (id);

alter table "public"."servises" add constraint "servises_pkey" PRIMARY KEY using index "servises_pkey";

alter table "public"."tokens" add constraint "tokens_service_fkey" FOREIGN KEY (service) REFERENCES servises(id) not valid;

alter table "public"."tokens" validate constraint "tokens_service_fkey";

grant delete on table "public"."servises" to "anon";

grant insert on table "public"."servises" to "anon";

grant references on table "public"."servises" to "anon";

grant select on table "public"."servises" to "anon";

grant trigger on table "public"."servises" to "anon";

grant truncate on table "public"."servises" to "anon";

grant update on table "public"."servises" to "anon";

grant delete on table "public"."servises" to "authenticated";

grant insert on table "public"."servises" to "authenticated";

grant references on table "public"."servises" to "authenticated";

grant select on table "public"."servises" to "authenticated";

grant trigger on table "public"."servises" to "authenticated";

grant truncate on table "public"."servises" to "authenticated";

grant update on table "public"."servises" to "authenticated";

grant delete on table "public"."servises" to "service_role";

grant insert on table "public"."servises" to "service_role";

grant references on table "public"."servises" to "service_role";

grant select on table "public"."servises" to "service_role";

grant trigger on table "public"."servises" to "service_role";

grant truncate on table "public"."servises" to "service_role";

grant update on table "public"."servises" to "service_role";


