revoke delete on table "public"."servises" from "anon";

revoke insert on table "public"."servises" from "anon";

revoke references on table "public"."servises" from "anon";

revoke select on table "public"."servises" from "anon";

revoke trigger on table "public"."servises" from "anon";

revoke truncate on table "public"."servises" from "anon";

revoke update on table "public"."servises" from "anon";

revoke delete on table "public"."servises" from "authenticated";

revoke insert on table "public"."servises" from "authenticated";

revoke references on table "public"."servises" from "authenticated";

revoke select on table "public"."servises" from "authenticated";

revoke trigger on table "public"."servises" from "authenticated";

revoke truncate on table "public"."servises" from "authenticated";

revoke update on table "public"."servises" from "authenticated";

revoke delete on table "public"."servises" from "service_role";

revoke insert on table "public"."servises" from "service_role";

revoke references on table "public"."servises" from "service_role";

revoke select on table "public"."servises" from "service_role";

revoke trigger on table "public"."servises" from "service_role";

revoke truncate on table "public"."servises" from "service_role";

revoke update on table "public"."servises" from "service_role";

alter table "public"."tokens" drop constraint "tokens_service_fkey";

alter table "public"."servises" drop constraint "servises_pkey";

drop index if exists "public"."servises_pkey";

drop table "public"."servises";

create table "public"."services" (
    "id" bigint generated by default as identity not null,
    "type" servise_types,
    "name" character varying,
    "description" text
);


CREATE UNIQUE INDEX servises_pkey ON public.services USING btree (id);

alter table "public"."services" add constraint "servises_pkey" PRIMARY KEY using index "servises_pkey";

alter table "public"."tokens" add constraint "tokens_service_fkey" FOREIGN KEY (service) REFERENCES services(id) not valid;

alter table "public"."tokens" validate constraint "tokens_service_fkey";

grant delete on table "public"."services" to "anon";

grant insert on table "public"."services" to "anon";

grant references on table "public"."services" to "anon";

grant select on table "public"."services" to "anon";

grant trigger on table "public"."services" to "anon";

grant truncate on table "public"."services" to "anon";

grant update on table "public"."services" to "anon";

grant delete on table "public"."services" to "authenticated";

grant insert on table "public"."services" to "authenticated";

grant references on table "public"."services" to "authenticated";

grant select on table "public"."services" to "authenticated";

grant trigger on table "public"."services" to "authenticated";

grant truncate on table "public"."services" to "authenticated";

grant update on table "public"."services" to "authenticated";

grant delete on table "public"."services" to "service_role";

grant insert on table "public"."services" to "service_role";

grant references on table "public"."services" to "service_role";

grant select on table "public"."services" to "service_role";

grant trigger on table "public"."services" to "service_role";

grant truncate on table "public"."services" to "service_role";

grant update on table "public"."services" to "service_role";


