revoke delete on table "public"."employees" from "anon";

revoke insert on table "public"."employees" from "anon";

revoke references on table "public"."employees" from "anon";

revoke select on table "public"."employees" from "anon";

revoke trigger on table "public"."employees" from "anon";

revoke truncate on table "public"."employees" from "anon";

revoke update on table "public"."employees" from "anon";

revoke delete on table "public"."employees" from "authenticated";

revoke insert on table "public"."employees" from "authenticated";

revoke references on table "public"."employees" from "authenticated";

revoke select on table "public"."employees" from "authenticated";

revoke trigger on table "public"."employees" from "authenticated";

revoke truncate on table "public"."employees" from "authenticated";

revoke update on table "public"."employees" from "authenticated";

revoke delete on table "public"."employees" from "service_role";

revoke insert on table "public"."employees" from "service_role";

revoke references on table "public"."employees" from "service_role";

revoke select on table "public"."employees" from "service_role";

revoke trigger on table "public"."employees" from "service_role";

revoke truncate on table "public"."employees" from "service_role";

revoke update on table "public"."employees" from "service_role";

alter table "public"."employees" drop constraint "employees_pkey";

drop index if exists "public"."employees_pkey";

drop table "public"."employees";

create table "public"."sys_params" (
    "id" bigint generated by default as identity not null,
    "name" character varying default '255'::character varying,
    "int_value" bigint,
    "string_value" character varying default '255'::character varying,
    "date_value" date,
    "uuid_value" uuid
);


alter table "public"."sys_params" enable row level security;

create table "public"."tenants" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "admin" bigint
);


create table "public"."tokens" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user" bigint not null,
    "service" bigint,
    "token" character varying not null default '255'::character varying
);


create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "provider" character varying default '255'::character varying,
    "provider_id" character varying default '255'::character varying,
    "email" character varying default '255'::character varying,
    "name" character varying default '255'::character varying,
    "void" boolean not null default true
);


CREATE UNIQUE INDEX "Tenants_pkey" ON public.tenants USING btree (id);

CREATE UNIQUE INDEX sys_params_pkey ON public.sys_params USING btree (id);

CREATE UNIQUE INDEX tokens_pkey ON public.tokens USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."sys_params" add constraint "sys_params_pkey" PRIMARY KEY using index "sys_params_pkey";

alter table "public"."tenants" add constraint "Tenants_pkey" PRIMARY KEY using index "Tenants_pkey";

alter table "public"."tokens" add constraint "tokens_pkey" PRIMARY KEY using index "tokens_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."tokens" add constraint "tokens_user_fkey" FOREIGN KEY ("user") REFERENCES users(id) not valid;

alter table "public"."tokens" validate constraint "tokens_user_fkey";

grant delete on table "public"."sys_params" to "anon";

grant insert on table "public"."sys_params" to "anon";

grant references on table "public"."sys_params" to "anon";

grant select on table "public"."sys_params" to "anon";

grant trigger on table "public"."sys_params" to "anon";

grant truncate on table "public"."sys_params" to "anon";

grant update on table "public"."sys_params" to "anon";

grant delete on table "public"."sys_params" to "authenticated";

grant insert on table "public"."sys_params" to "authenticated";

grant references on table "public"."sys_params" to "authenticated";

grant select on table "public"."sys_params" to "authenticated";

grant trigger on table "public"."sys_params" to "authenticated";

grant truncate on table "public"."sys_params" to "authenticated";

grant update on table "public"."sys_params" to "authenticated";

grant delete on table "public"."sys_params" to "service_role";

grant insert on table "public"."sys_params" to "service_role";

grant references on table "public"."sys_params" to "service_role";

grant select on table "public"."sys_params" to "service_role";

grant trigger on table "public"."sys_params" to "service_role";

grant truncate on table "public"."sys_params" to "service_role";

grant update on table "public"."sys_params" to "service_role";

grant delete on table "public"."tenants" to "anon";

grant insert on table "public"."tenants" to "anon";

grant references on table "public"."tenants" to "anon";

grant select on table "public"."tenants" to "anon";

grant trigger on table "public"."tenants" to "anon";

grant truncate on table "public"."tenants" to "anon";

grant update on table "public"."tenants" to "anon";

grant delete on table "public"."tenants" to "authenticated";

grant insert on table "public"."tenants" to "authenticated";

grant references on table "public"."tenants" to "authenticated";

grant select on table "public"."tenants" to "authenticated";

grant trigger on table "public"."tenants" to "authenticated";

grant truncate on table "public"."tenants" to "authenticated";

grant update on table "public"."tenants" to "authenticated";

grant delete on table "public"."tenants" to "service_role";

grant insert on table "public"."tenants" to "service_role";

grant references on table "public"."tenants" to "service_role";

grant select on table "public"."tenants" to "service_role";

grant trigger on table "public"."tenants" to "service_role";

grant truncate on table "public"."tenants" to "service_role";

grant update on table "public"."tenants" to "service_role";

grant delete on table "public"."tokens" to "anon";

grant insert on table "public"."tokens" to "anon";

grant references on table "public"."tokens" to "anon";

grant select on table "public"."tokens" to "anon";

grant trigger on table "public"."tokens" to "anon";

grant truncate on table "public"."tokens" to "anon";

grant update on table "public"."tokens" to "anon";

grant delete on table "public"."tokens" to "authenticated";

grant insert on table "public"."tokens" to "authenticated";

grant references on table "public"."tokens" to "authenticated";

grant select on table "public"."tokens" to "authenticated";

grant trigger on table "public"."tokens" to "authenticated";

grant truncate on table "public"."tokens" to "authenticated";

grant update on table "public"."tokens" to "authenticated";

grant delete on table "public"."tokens" to "service_role";

grant insert on table "public"."tokens" to "service_role";

grant references on table "public"."tokens" to "service_role";

grant select on table "public"."tokens" to "service_role";

grant trigger on table "public"."tokens" to "service_role";

grant truncate on table "public"."tokens" to "service_role";

grant update on table "public"."tokens" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


